### ISSUE TITLE
Show relevant environment information in AWS console

### ISSUE THREAD

**Issue by mlafeldt** [Luzifer/awsenv#11]
With `awsenv`, it's currently hard to figure out in which account one operates. This can contribute to applying actions in the wrong account.

For example, this is what the indicator in the upper right corner looks like for the envrionment `wonderland-prod`:

![awsenv](https://cloud.githubusercontent.com/assets/158074/18248375/f1bf1872-7377-11e6-99ed-007f4b1a8206.png)

Unfortunately, it's the same for `wonderland-stage`.

Is it possible to, for example, remove the `awsenv-` prefix to save some space?

**Comment by Luzifer** [comment]
From the commit message:

> As this prefix just shows what authentication method was used by the corresponding user it had no special function other than being there. Until now I did not see any other tool doing this so I'm dropping this prefix in order to increase readability of the login name.

Change included in `v0.11.0`

**Comment by mlafeldt** [comment]
Thanks! 🎉
